### ISSUE TITLE
Zzz

### ISSUE THREAD

**Issue by JesusChapman** [spawmc/breakjaro-linux#1]
Manjaro GOD

**Comment by spxwnmc** [comment]
use termux as a real distribution? zzz

**Comment by kyb3rcipher** [comment]
> use termux as a real distribution? zzz

era humillarlo no matarlo!!!

**Comment by JesusChapman** [comment]
Pues tengo mi portátil y uso manjaro como principal.

**Comment by spxwnmc** [comment]
> Pues tengo mi portátil y uso manjaro como principal.

??

**Comment by JesusChapman** [comment]
ManjaroGOOD

**Comment by spxwnmc** [comment]
> ManjaroGOOD

Ya cállate puto naco

**Comment by JesusChapman** [comment]
No

**Comment by kyb3rcipher** [comment]
ya paso un año no me jodan
